import { statSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  PLANNING_NOTICES,
  PLANNING_REQUEST_IDS,
  PLANNING_REQUEST_TITLES,
  PLANNING_SECTION_GUIDE,
  PLANNING_SECTION_TITLES,
  ROADMAP_STATE_PHRASES,
  VANTAGE_OQ_PREFERENCE,
  agentSectionsWithEntries,
  applyPlanningFilter,
  badgeFor,
  badgeText,
  buildPlanningIndex,
  codeSpan,
  dependsOnLabel,
  derivePlanningSections,
  filterKeepsQuestion,
  findDocument,
  noticeText,
  parsePlanningFilter,
  planningAgentRequest,
  planningLink,
  planningSectionGuide,
  questionFor,
  sectionExplanation,
  type FilteredPlanningSections,
  type PlanningAgentRequestOptions,
  type PlanningRequestId,
  type PlanningBadge,
  type PlanningIndex,
  type PlanningRoadmap,
  type PlanningSectionId,
  type PlanningSections,
  type PlanningSources,
  type UnderstoodPlanningFilter,
  type QuestionRef,
  type QuestionState,
} from "../../../vantage-md/src/planning/index.js";
import { VANTAGE_OQ_STATUS } from "../../../vantage-md/src/vantageDirectives.js";
import { Listing, listCandidates, readCandidate } from "../core/candidates.js";
import {
  ConfigError,
  configPathFor,
  loadConfig,
  type LoadOptions,
} from "../core/config.js";
import {
  FILTER_RELEASE_NAME,
  PLANNING_PAGE_RELEASE_NAME,
  declaredTargets,
  noteTargets,
  predatesFilter,
  predatesPlanningPage,
  refuseTargets,
  type DeclaredTarget,
} from "../core/target.js";
import { repositoryRoot } from "../core/projectRoot.js";
import {
  ensureSpace,
  mainCheckoutOf,
  spaceIdOf,
  type Space,
} from "../core/space.js";
import { oneLine } from "../core/text.js";
import { EXIT_ENVIRONMENT, EXIT_OK, EXIT_USAGE } from "../exit.js";
import type { Io } from "../io.js";
import { VERSION } from "../version.js";

/**
 * `vantage-check index`: the planning page, for an agent
 * (`docs/reference/planning-index.md` §13).
 *
 * It scans the *project root* (the nearest ancestor of the working directory
 * holding `.git` or `.vantage.toml`, else the working directory itself), builds
 * the planning index from every candidate there, and prints the page's
 * sections for the chosen roadmap, each titled and explained as the page
 * explains it, then that roadmap with each link's badge inline. Every line of
 * it is a derivation `vantage-md` also hands the viewer, so the page and the
 * CLI cannot disagree (P7). `--request` prints instead the request the page's
 * Copy agent request buttons copy, generated by the same function
 * (`planningAgentRequest`).
 *
 * With several roadmaps it lists them all and chooses one as the page does,
 * with no memory between runs: `--roadmap`, else the one nearest the root
 * (§13).
 *
 * `--filter` shows only the entries a planning filter keeps, as the page's
 * Filter box does, and prints a root-relative link to that filtered page
 * (§13.4). The filter is parsed, applied and linked by vantage-md's planning
 * module, the page's own reader (F1). The link carries the checkout's space id
 * (§13.6), which the command makes in `.vantage/space` the first time it
 * prints one: the one file it ever writes.
 *
 * It reports and does not judge, so it never exits 1: 0 when it ran, 2 for bad
 * arguments or a bad config, a filter it cannot read or one with a `path:`
 * term, with or without its `-`, that matches no path, 3 when it could not
 * run, which includes a project with more candidates than `max-candidates`
 * (Plan Q7). A text term that matches nothing is an answer, not an error, and
 * exits 0.
 */
export interface IndexOptions {
  format: "text" | "json";
  /** An explicit `.vantage.toml`. It chooses the config, never the project. */
  configPath?: string;
  /** Ignore any `.vantage.toml` and use the built-in defaults. */
  noConfig?: boolean;
  /**
   * `--roadmap`: the roadmap Needs you follows, repo-relative, one leading
   * `./` dropped. It has to be one that routes; without it, the default
   * roadmap is chosen.
   */
  roadmap?: string;
  /**
   * `--request`: print the agent request for these sections instead of the
   * index. Empty asks for every request, the four agent sections and `compact`, as Copy all agent requests
   * does.
   */
  request?: PlanningRequestId[];
  /**
   * `--filter`: a planning filter's text, every value given joined with one
   * space (`docs/reference/planning-index.md` §13.4). Empty, or white space
   * alone, is no filter, and the output is byte for byte a run without it.
   */
  filter?: string;
}

/**
 * The JSON format's own version, which is not the tool's. `check`'s JSON calls
 * the tool's version `version`; this one says `toolVersion` for that, so the
 * word here can mean the format, and a later change to the shape can say so.
 */
export const INDEX_FORMAT_VERSION = 2;

/** A candidate project, scanned: the index and the text each document had. */
interface ScannedProject {
  root: string;
  index: PlanningIndex;
  /** Every candidate, for narrowing each document's links on output. */
  candidates: ReadonlySet<string>;
  /** Each read candidate's text, for the roadmap's badged source. */
  sources: ReadonlyMap<string, string>;
}

export function indexCommand(options: IndexOptions, io: Io): number {
  // The config file never moves the project: `--config /tmp/x.toml` still
  // scans the tree the command was run in (Plan Q16).
  const root = repositoryRoot(io.cwd) ?? io.cwd;

  // The root's own config and nothing above it, the one file the server
  // reads for this repository (docs/reference/repo-config.md §3.2), so the
  // page and this command read the same `[planning]` (P7).
  const load: LoadOptions = {
    from: root,
    stopAt: root,
    cwd: io.cwd,
    ...(options.configPath === undefined
      ? {}
      : { explicitPath: resolve(io.cwd, options.configPath) }),
    ...(options.noConfig === undefined ? {} : { noConfig: options.noConfig }),
  };
  let loaded;
  let targets;
  try {
    // The target first, as `check` reads it (core/target.ts).
    targets = declaredTargets([configPathFor(load)], io.cwd);
    const refused = refuseTargets(targets, io);
    if (refused !== undefined) return refused;
    loaded = loadConfig(load);
  } catch (error) {
    if (!(error instanceof ConfigError)) throw error;
    io.err(`vantage-check: ${error.message}\n`);
    return EXIT_USAGE;
  }
  noteTargets(targets, io);
  for (const warning of loaded.warnings) {
    io.err(`vantage-check: warning: ${warning}\n`);
  }

  // What a filter's text means depends on nothing in the tree, so one it
  // cannot read is refused before the scan, past max-candidates too, and
  // never partly applied (F3, §13.4). The message is the whole answer, as
  // `--roadmap`'s is: it says what the language reads.
  const parsed =
    options.filter === undefined ? null : parsePlanningFilter(options.filter);
  if (parsed?.kind === "not-understood") {
    io.err(
      `vantage-check: --filter: ${PLANNING_NOTICES.filterNotUnderstood(parsed)}\n`,
    );
    return EXIT_USAGE;
  }
  const filter = parsed?.kind === "understood" ? parsed : null;

  const project = scanProject(root, loaded.planning);
  const { index } = project;
  // Past max-candidates nothing was read, so there is nothing to hold
  // `--roadmap` to, and the refusal is the answer whatever it says.
  const asked =
    options.roadmap === undefined || index.refused
      ? undefined
      : options.roadmap.replace(/^\.\//, "");
  const sections = index.refused
    ? null
    : derivePlanningSections(index, { roadmap: asked ?? null });

  // A path that is not a roadmap that routes falls back to the default in
  // the sections, as on the page; asked for by name, it is a bad argument.
  if (sections !== null && asked !== undefined) {
    if (sections.chosenRoadmap !== asked) {
      const routing = sections.roadmaps
        .filter((roadmap) => roadmap.state === "routes")
        .map((roadmap) => roadmap.path);
      const known =
        routing.length === 0
          ? "there is no roadmap"
          : `the roadmaps are: ${routing.join(", ")}`;
      io.err(
        `vantage-check: --roadmap ${options.roadmap} is not a roadmap here; ${known}\n`,
      );
      return EXIT_USAGE;
    }
  }

  // Applied to the sections of the whole index, never to the index (F2).
  // Past max-candidates there are no sections, so nothing is applied and no
  // term is held to the tree: the refusal is the answer (§13.4).
  const applied =
    sections === null || filter === null
      ? null
      : appliedFilter(
          options.filter ?? "",
          applyPlanningFilter(index, sections, filter),
          sections,
        );
  // The page applies an unmatched term, keeps nothing or excludes nothing, and
  // names it. Here it is the agent's likeliest mistake, a mistyped path, so it
  // stops before the human is handed an empty page, or a fuller one than the
  // agent meant (F5, §13.4). A text term that matches nothing is not one.
  if (applied !== null && applied.filtered.summary.unmatched.length > 0) {
    for (const term of applied.filtered.summary.unmatched) {
      io.err(
        `vantage-check: --filter: ${PLANNING_NOTICES.filterUnmatched(term)}\n`,
      );
    }
    return EXIT_USAGE;
  }

  // A link is about to be printed, so the checkout's space id is found or
  // made now, and never for a run that prints none: `--request`, an
  // unmatched term, a refused project (§13.6).
  if (applied !== null && options.request === undefined) {
    applied.space = spaceOut(project.root, io);
    applied.link = linkFor(applied.filtered, applied.unfiltered, applied.space);
  }

  if (options.request !== undefined) {
    if (sections !== null) {
      requestOut(project, sections, options.request, io, applied, filter);
    }
  } else if (options.format === "json") {
    io.out(
      renderJson(
        project,
        sections,
        filter === null ? undefined : (applied ?? null),
      ),
    );
  } else if (sections !== null) {
    io.out(
      renderText(
        project,
        applied?.filtered.sections ?? sections,
        applied === null
          ? null
          : {
              head: filterHead(project, applied, targets),
              canonical: applied.filtered.summary.canonical,
              nothingMatches:
                PLANNING_NOTICES.nothingMatches(
                  applied.filtered.summary,
                  "checker",
                )
                  ?.map(noticeText)
                  .join("\n") ?? null,
            },
      ),
    );
  }

  if (index.refused) {
    io.err(
      `vantage-check: ${PLANNING_NOTICES.refused(index.candidateCount, index.config.maxCandidates)}\n`,
    );
    return EXIT_ENVIRONMENT;
  }
  return EXIT_OK;
}

/**
 * Every candidate under `root`, read the way the planning endpoint reads it,
 * into one batch, and the index built from that batch. Past `max-candidates`
 * nothing is opened at all, as the server opens nothing (§16).
 */
function scanProject(
  root: string,
  config: PlanningSources["config"],
): ScannedProject {
  const candidates = listCandidates(new Listing(root), config);
  const refused = candidates.length > config.maxCandidates;
  const sources: PlanningSources = {
    config,
    candidateCount: candidates.length,
    refused,
    files: [],
    skipped: [],
    unreadable: [],
  };
  const texts = new Map<string, string>();
  if (!refused) {
    for (const path of candidates) {
      const entry = readCandidate(root, path, config.maxFileBytes);
      switch (entry.kind) {
        case "file":
          sources.files.push({ path, content: entry.content });
          texts.set(path, entry.content);
          break;
        case "skipped":
          sources.skipped.push({ path, size: entry.size });
          break;
        case "unreadable":
          sources.unreadable.push({ path, reason: entry.reason });
          break;
        case "absent":
          // Listed a moment ago and gone now: it is no longer a candidate.
          break;
      }
    }
  }
  return {
    root,
    index: buildPlanningIndex(sources),
    candidates: new Set(candidates),
    sources: texts,
  };
}

/** A filter applied to a project's sections, and the link to the page it gives. */
interface AppliedFilter {
  /** The text as given: every `--filter` value, joined with one space. */
  text: string;
  filtered: FilteredPlanningSections;
  /** The sections it was applied to, which a request's blocked-on facts read (§6.15). */
  unfiltered: PlanningSections;
  /**
   * The root-relative link to the filtered planning page (§13.5), naming the
   * chosen roadmap when two or more roadmaps can be chosen, so the human's
   * Needs you follows the roadmap the agent checked, whatever they last picked,
   * and then the checkout's space id once `space` holds one (§13.6).
   */
  link: string;
  /**
   * The checkout's space, found or made just before the link is printed, and
   * `null` until then.
   */
  space: Space | null;
}

function appliedFilter(
  text: string,
  filtered: FilteredPlanningSections,
  unfiltered: PlanningSections,
): AppliedFilter {
  return {
    text,
    filtered,
    unfiltered,
    link: linkFor(filtered, unfiltered, null),
    space: null,
  };
}

/** The link to the filtered page, with `space`'s id when it has one. */
function linkFor(
  filtered: FilteredPlanningSections,
  unfiltered: PlanningSections,
  space: Space | null,
): string {
  const routing = unfiltered.roadmaps.filter((r) => r.state === "routes");
  return planningLink(filtered.summary.canonical, {
    roadmap: routing.length >= 2 ? unfiltered.chosenRoadmap : null,
    space: spaceIdOf(space),
  });
}

/**
 * The checkout's space (§13.6), found or made, with a warning on stderr when
 * it has no id to give the link: a `.vantage/space` that holds none, which is
 * left as it is, or one that could not be made. The link is printed without
 * `space=` then, as a checker before the space id printed it.
 */
function spaceOut(root: string, io: Io): Space {
  const space = ensureSpace(root);
  if (space.kind === "malformed") {
    io.err(
      `vantage-check: warning: ${space.file} does not hold a space id, so the planning link names no checkout. Remove the file to have a new one made.\n`,
    );
  } else if (space.kind === "unwritable") {
    io.err(
      `vantage-check: warning: could not make ${space.file}, so the planning link names no checkout: ${space.reason}\n`,
    );
  }
  return space;
}

/**
 * The checker cannot learn the address the human opens Vantage at (§13.5), so
 * the link is root-relative, and this says the two ways to use it.
 */
const PASTE_HINT =
  "Press / on the planning page and paste this line, or put the scheme, host and port you open Vantage at in front of the link.";

/**
 * The hint line under it when the link carries a space id (§13.6), which says
 * what `space=` does: with an address in front, a Vantage serving several
 * projects opens the one whose `.vantage/space` holds it. In a linked
 * worktree the id is the worktree's own, and a Vantage that serves only its
 * main checkout opens that one, so the line names it.
 */
function spaceHint(root: string, space: Space): string | null {
  if (spaceIdOf(space) === null) return null;
  const main = mainCheckoutOf(root);
  return main === null
    ? "space= is this checkout's id, kept in .vantage/space: with an address in front, the link opens this project's page even where one Vantage serves several."
    : `space= is this worktree's id, kept in its own .vantage/space: with an address in front, the link opens this worktree's page even where one Vantage serves several, or the page of its main checkout ${codeSpan(main)} where only that is served.`;
}

/**
 * Whether `root` is a linked worktree: its `.git` is a file, not a directory.
 * A root found by its `.vantage.toml` alone has no `.git`, and is not one.
 */
function isLinkedWorktree(root: string): boolean {
  try {
    return statSync(join(root, ".git")).isFile();
  } catch {
    return false;
  }
}

/**
 * What the text prints before everything else under a filter (§13.4): the
 * filter notice, its clauses included, then the `Planning page:` line and its
 * hint lines (§13.5). A second hint says what `space=` does when the link
 * carries one (§13.6), a third when the root is a linked worktree, since the
 * page shows the checkout the human's Vantage serves, and a fourth when the
 * run's `target` names a release before the filter's, which says too that a
 * viewer has no planning page at all when it names one before the page's
 * (§13.5).
 */
function filterHead(
  project: ScannedProject,
  applied: AppliedFilter,
  targets: readonly DeclaredTarget[],
): string {
  const lines = PLANNING_NOTICES.filtered(
    applied.filtered.summary,
    "checker",
  ).map(noticeText);
  lines.push(`Planning page: ${applied.link}`, `  ${PASTE_HINT}`);
  const space =
    applied.space === null ? null : spaceHint(project.root, applied.space);
  if (space !== null) lines.push(`  ${space}`);
  if (isLinkedWorktree(project.root)) {
    // The root as code, as §13.5 quotes the line, so a path holding a space
    // or a `:` reads as one.
    lines.push(
      `  ${codeSpan(project.root)} is a linked worktree: the page shows the checkout your Vantage serves, which may not hold these documents as they are here.`,
    );
  }
  // The oldest reader decides: one before the planning page has no page to
  // open, and the readers after it, up to the filter's release, see every
  // entry.
  if (targets.some(({ target }) => predatesPlanningPage(target))) {
    lines.push(
      `  A Vantage viewer before ${PLANNING_PAGE_RELEASE_NAME} has no planning page, and one before ${FILTER_RELEASE_NAME} ignores this filter and shows every entry.`,
    );
  } else if (targets.some(({ target }) => predatesFilter(target))) {
    lines.push(
      `  A Vantage viewer before ${FILTER_RELEASE_NAME} ignores this filter and shows every entry.`,
    );
  }
  return lines.join("\n");
}

/** `text` as one POSIX shell word: single-quoted, each `'` written `'\''`. */
function shellQuote(text: string): string {
  return `'${text.replaceAll("'", "'\\''")}'`;
}

/**
 * `--request`: exactly what the page's buttons copy for the same sections
 * (the page passes the repository's root path, as this passes the project
 * root), and a newline. With nothing to ask for, stdout stays empty, as the
 * page shows no button, and stderr says why.
 *
 * Under a filter, the request covers the filtered sections and carries the
 * `Filter:` line, as Copy agent request does on the filtered page (§6.2).
 */
function requestOut(
  project: ScannedProject,
  sections: PlanningSections,
  asked: readonly PlanningRequestId[],
  io: Io,
  applied: AppliedFilter | null,
  filter: UnderstoodPlanningFilter | null,
): void {
  const ids = asked.length === 0 ? PLANNING_REQUEST_IDS : asked;
  const options: PlanningAgentRequestOptions = {
    repository: project.root,
    ids,
  };
  if (applied !== null) {
    // The `Filter:` line carries the canonical text less its unmatched terms
    // (§6.2). Here there are none, or the command has already exited 2.
    const { requestText, canonical } = applied.filtered.summary;
    options.filter = {
      text: requestText ?? canonical,
      unfiltered: applied.unfiltered,
      // `compact` lists from the whole index, so it needs the filter's own
      // question test.
      ...(filter === null
        ? {}
        : { keeps: (q) => filterKeepsQuestion(filter, q) }),
    };
  }
  const request = planningAgentRequest(
    project.index,
    applied?.filtered.sections ?? sections,
    options,
  );
  if (request !== null) {
    io.out(`${request}\n`);
    return;
  }
  // A section with no entries is empty, or not shown at all (no roadmap, or
  // no stages): "has no entries" is true of both.
  const empty = PLANNING_REQUEST_IDS.filter((id) => ids.includes(id));
  io.err(
    `vantage-check: nothing to ask an agent: ${andList(empty.map((id) => PLANNING_REQUEST_TITLES[id]))} ${empty.length === 1 ? "has" : "have"} no entries${applied === null ? "" : " the filter keeps"}\n`,
  );
}

/** `a`, `a and b`, `a, b and c`. */
function andList(items: readonly string[]): string {
  if (items.length <= 1) return items.join("");
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

/** A link from a roadmap, as the JSON lists it. */
interface RoadmapLink {
  line: number;
  target: string;
  fragment: string | null;
  badge: PlanningBadge | null;
  badgeText: string | null;
}

/**
 * The index as the JSON prints it. The index keeps every repo-relative link,
 * because a target's candidacy can change between scans; the output narrows
 * each document's links to what §3.2 calls a link, one to another
 * candidate.
 */
function narrowed(project: ScannedProject): PlanningIndex {
  const { index, candidates } = project;
  return {
    ...index,
    documents: index.documents.map((doc) => ({
      ...doc,
      links: doc.links.filter(
        (link) => link.target !== doc.path && candidates.has(link.target),
      ),
    })),
  };
}

/** One roadmap's links, or none when it was not read (§13). */
function roadmapLinks(
  project: ScannedProject,
  narrowedIndex: PlanningIndex,
  path: string,
): RoadmapLink[] {
  const { index } = project;
  const roadmap = findDocument(narrowedIndex, path);
  if (roadmap === undefined) return [];
  return roadmap.links.map((link) => {
    const badge = badgeFor(index, roadmap.path, {
      path: link.target,
      fragment: link.fragment,
    });
    return {
      line: link.line,
      target: link.target,
      fragment: link.fragment,
      badge,
      badgeText: badge === null ? null : badgeText(badge),
    };
  });
}

/**
 * The machine-readable index, format version 2 (§13). A refused project
 * has no sections, no roadmaps and no guide to them, so all three are `null`
 * there, and `index.refused` and `index.candidateCount` say why.
 *
 * `sectionGuide` is every section in page order with its id, the `sections`
 * key holding its entries, its title, its explanation line and its actor. It
 * is a key of its own, added without a new version: an added key changes no
 * existing one's meaning.
 *
 * `roadmaps` has one entry per entry of `sections.roadmaps`, in the same
 * order, each with the links version 1 printed as `roadmap`; they are empty
 * unless the file was read, which is the `routes` and `done` states.
 *
 * `filter` is the last key, and only under `--filter` (§13.4): `undefined`
 * leaves it out, so every key before it is byte for byte a run without the
 * flag, and `null` is a refused project's, which has no sections to filter.
 * Every existing key keeps its meaning under a filter: `sections` and
 * `roadmaps` are the whole index's, since `needsYouCount` and
 * `nothingNeedsYou` are defined over it, and the filtered view is this key's.
 */
function renderJson(
  project: ScannedProject,
  sections: PlanningSections | null,
  filter?: AppliedFilter | null,
): string {
  const index = narrowed(project);
  return `${JSON.stringify(
    {
      tool: "vantage-check",
      toolVersion: VERSION,
      version: INDEX_FORMAT_VERSION,
      root: project.root,
      index,
      sections,
      sectionGuide: sections === null ? null : planningSectionGuide(sections),
      roadmaps:
        sections === null
          ? null
          : sections.roadmaps.map(({ path, state }) => ({
              path,
              state,
              chosen: path === sections.chosenRoadmap,
              links: roadmapLinks(project, index, path),
            })),
      ...(filter === undefined
        ? {}
        : { filter: filter === null ? null : filterJson(filter) }),
    },
    null,
    2,
  )}\n`;
}

/**
 * The JSON `filter` key's value (§13.4), in its documented key order, built key
 * by key: the summary holds names (`requestText`, `unmatched`,
 * `onOtherRoadmaps`) that are not keys of it, and a script reads these keys,
 * so each keeps its meaning (P0, §6.19). `unknownKeys` lists the words alone,
 * which the summary pairs with the terms they open. `link` is always
 * root-relative, and carries the checkout's space id when it has one (§13.6).
 */
function filterJson(applied: AppliedFilter) {
  const { summary, sections } = applied.filtered;
  return {
    text: applied.text,
    canonical: summary.canonical,
    link: applied.link,
    documents: { kept: summary.documents.kept, of: summary.documents.of },
    entries: { shown: summary.entries.shown, of: summary.entries.of },
    openQuestions: summary.openQuestions,
    blockedLeftOut: summary.blockedLeftOut,
    otherRoadmaps: summary.otherRoadmaps.map(({ path, count }) => ({
      path,
      count,
    })),
    waitsOutside: summary.waitsOutside.map(({ path, target }) => ({
      path,
      target,
    })),
    unknownKeys: summary.unknownKeys.map(({ key }) => key),
    sections,
  };
}

/* ------------------------------------------------------------------ *
 * Text
 * ------------------------------------------------------------------ */

/** A question's state as the page marks it: `💬`, `💬 🤷`, `🔒` or `✅`. */
function stateGlyph(state: QuestionState, preference: boolean): string {
  if (state === "blocked") return VANTAGE_OQ_STATUS.blocked;
  if (state === "answered") return VANTAGE_OQ_STATUS.settled;
  return preference
    ? `${VANTAGE_OQ_STATUS.open} ${VANTAGE_OQ_PREFERENCE}`
    : VANTAGE_OQ_STATUS.open;
}

/**
 * One question: where its item starts, its state and its title, so a reader
 * can open the file at the line and read the question there.
 */
function questionLine(index: PlanningIndex, ref: QuestionRef): string {
  const q = questionFor(index, ref);
  if (q === undefined) return `${ref.path}:${ref.line}  ${ref.id ?? ""}`;
  return `${q.path}:${q.unitLine}  ${stateGlyph(q.state, q.preference)} ${oneLine(q.title)}`;
}

/** A document, with the badge a link to it would carry. */
function documentLine(index: PlanningIndex, path: string): string {
  const badge = badgeFor(index, "", { path, fragment: null });
  return badge === null ? path : `${path}  [${badgeText(badge)}]`;
}

function bytes(n: number): string {
  return `${n.toLocaleString("en-US")} bytes`;
}

/** A heading with its count, then one indented line per entry. */
function block(title: string, lines: readonly string[]): string | null {
  if (lines.length === 0) return null;
  return [
    `${title} (${lines.length.toLocaleString("en-US")})`,
    ...lines.map((line) => `  ${line}`),
  ].join("\n");
}

/**
 * One of the page's sections: its title and count, its explanation line
 * unindented beneath, so only an entry is ever indented, then its entries.
 *
 * On the page "you" is the person reading it; an agent reads this output, so
 * a section whose actor is `you` says whom it means — *Needs you (4) · for
 * the human* — and an agent does not take "Rule each" as addressed to it.
 */
function section(
  id: PlanningSectionId,
  sections: PlanningSections,
  lines: readonly string[],
): string | null {
  if (lines.length === 0) return null;
  const forWhom =
    PLANNING_SECTION_GUIDE[id].actor === "you" ? " · for the human" : "";
  return [
    `${PLANNING_SECTION_TITLES[id]} (${lines.length.toLocaleString("en-US")})${forWhom}`,
    sectionExplanation(id, sections),
    ...lines.map((line) => `  ${line}`),
  ].join("\n");
}

/** `1 needs you`, `4 need you`. */
function needsYouCount(n: number): string {
  return `${n.toLocaleString("en-US")} ${n === 1 ? "needs" : "need"} you`;
}

/**
 * One line of the Roadmaps block: the path, then what it gives or why not. A
 * `done` roadmap was read, and its links are in the JSON, so it is said to be
 * ignored rather than not read; every other state is one the file was not
 * read in.
 */
function roadmapLine(roadmap: PlanningRoadmap, chosen: string | null): string {
  if (roadmap.state === "done") {
    return `${roadmap.path}  ignored: ${ROADMAP_STATE_PHRASES.done}`;
  }
  if (roadmap.state !== "routes") {
    return `${roadmap.path}  not read: ${ROADMAP_STATE_PHRASES[roadmap.state]}`;
  }
  const line = `${roadmap.path}  ${needsYouCount(roadmap.needsYouCount)}`;
  return roadmap.path === chosen ? `${line}  (chosen)` : line;
}

/**
 * The page's sections in page order, each hidden when empty and explained
 * under its heading, with the notices where the page shows them; a line
 * naming `--request` when an agent section has entries; then the chosen
 * roadmap's source with a badge in brackets after each badged link. With two
 * or more roadmaps, in any state, a Roadmaps block lists them before Needs
 * you; with one or none there is no such block.
 *
 * Under a filter, `sections` are the filtered ones and `filter.head` is
 * `filterHead`'s, printed first (§13.4). Everything after it is the same
 * layout over the filtered sections: *Nothing needs you* in its filtered form,
 * the Roadmaps block with the filtered counts, and a `--request` line that
 * carries the filter, shell-quoted. The roadmap's source is the index's, and
 * unchanged.
 *
 * A filter that keeps no entry has `filter.nothingMatches`, the page's words
 * for it: *Nothing matches* and its reason line stand where the sections
 * would, after the Roadmaps block, and *Nothing this filter keeps needs you*
 * is not printed, as the page does not show it.
 */
function renderText(
  project: ScannedProject,
  sections: PlanningSections,
  filter: {
    head: string;
    canonical: string;
    nothingMatches: string | null;
  } | null = null,
): string {
  const { index } = project;
  const { config } = index;
  const blocks: (string | null)[] = [];
  if (filter !== null) blocks.push(filter.head);
  const nothingMatches = filter?.nothingMatches ?? null;

  const notices: string[] = [];
  if (sections.nothingNeedsYou && nothingMatches === null) {
    notices.push(
      filter === null
        ? PLANNING_NOTICES.nothingNeedsYou
        : PLANNING_NOTICES.nothingFilteredNeedsYou,
    );
  }
  const roadmapNotice = PLANNING_NOTICES.roadmapNotice(
    config,
    sections.roadmaps,
  );
  if (roadmapNotice !== null) notices.push(roadmapNotice);
  if (sections.onOtherRoadmaps.length > 0) {
    notices.push(
      `${PLANNING_NOTICES.otherRoadmaps(sections.onOtherRoadmaps.length)} Choose one with --roadmap <path>.`,
    );
  }
  if (notices.length > 0) blocks.push(notices.join("\n"));

  if (sections.roadmaps.length >= 2) {
    blocks.push(
      block(
        "Roadmaps",
        sections.roadmaps.map((r) => roadmapLine(r, sections.chosenRoadmap)),
      ),
    );
  }
  // Every section below is empty, and not printed.
  if (nothingMatches !== null) blocks.push(nothingMatches);

  blocks.push(
    section(
      "needs-you",
      sections,
      sections.needsYou.map((ref) => {
        const line = questionLine(index, ref);
        return ref.heading === null ? line : `${line}  (${ref.heading})`;
      }),
    ),
  );
  blocks.push(
    section(
      "unrouted",
      sections,
      (sections.unrouted ?? []).map((ref) => questionLine(index, ref)),
    ),
  );
  blocks.push(
    section(
      "waiting",
      sections,
      sections.waiting.map((entry) =>
        entry.kind === "question"
          ? questionLine(index, entry.question)
          : `${entry.path}  blocked on ${entry.waitingOn.map(dependsOnLabel).join(", ")}`,
      ),
    ),
  );

  if (!sections.stagesDeclared) blocks.push(PLANNING_NOTICES.noStages);
  for (const [id, paths] of [
    ["ready", sections.ready],
    ["graduate", sections.graduate],
    ["disagrees", sections.disagrees],
  ] as const) {
    blocks.push(
      section(
        id,
        sections,
        (paths ?? []).map((path) => documentLine(index, path)),
      ),
    );
  }

  blocks.push(
    section(
      "skipped",
      sections,
      sections.skipped.map(
        (s) =>
          `${s.path}  ${bytes(s.size)}, over max-file-bytes (${bytes(config.maxFileBytes)})`,
      ),
    ),
  );
  blocks.push(
    section(
      "could-not-read",
      sections,
      sections.unreadable.map((u) => `${u.path}  ${u.reason}`),
    ),
  );
  // What an agent's sections ask for is a command away; say which.
  if (agentSectionsWithEntries(sections).length > 0) {
    blocks.push(
      filter === null
        ? "Agent requests: vantage-check index --request"
        : `Agent requests: vantage-check index --request --filter ${shellQuote(filter.canonical)}`,
    );
  }

  const roadmap =
    sections.chosenRoadmap === null
      ? undefined
      : findDocument(index, sections.chosenRoadmap);
  const source =
    roadmap === undefined ? undefined : project.sources.get(roadmap.path);
  if (roadmap !== undefined && source !== undefined) {
    blocks.push(
      `Roadmap: ${roadmap.path}\n\n${badged(index, roadmap.path, roadmap.links, source).replace(/\n+$/, "")}`,
    );
  }

  return `${blocks.filter((b) => b !== null).join("\n\n")}\n`;
}

/** `source`, with ` [<badge>]` inserted just past every link that has one. */
function badged(
  index: PlanningIndex,
  from: string,
  links: PlanningIndex["documents"][number]["links"],
  source: string,
): string {
  const inserts = links
    .map((link) => {
      const badge = badgeFor(index, from, {
        path: link.target,
        fragment: link.fragment,
      });
      return badge === null
        ? null
        : { at: link.endOffset, text: ` [${badgeText(badge)}]` };
    })
    .filter((insert) => insert !== null)
    .sort((a, b) => b.at - a.at);
  let out = source;
  for (const { at, text } of inserts) {
    out = `${out.slice(0, at)}${text}${out.slice(at)}`;
  }
  return out;
}
